const MODEL_TABLE_TITLE = '模型库存统计';

const OUT_OF_STOCK_TABLE_TITLE = '缺货统计';

const SKU_ANALYSIS_TABLE_TITLE = '历史销量/库存走势';

const SALE_FORECAST_TABLE_TITLE = '销量库存趋势'

export {
  MODEL_TABLE_TITLE,
  OUT_OF_STOCK_TABLE_TITLE,
  SKU_ANALYSIS_TABLE_TITLE,
  SALE_FORECAST_TABLE_TITLE,


}